name: π¥ λ°”κΎΈκ³  μ‹¶μ€ λ‚΄μ©!
description: μμ • λ° μ‚­μ ν•  λ‚΄μ©
title: "[λ‚΄μ© μμ • λ° μ‚­μ ] <μ λ©>"
labels: ["π¥ λ°”κΎΈκ³  μ‹¶μ€ λ‚΄μ©!"]
body:
- type: input
  id: duplicate
  attributes:
    label: μ΄μ μ¤‘λ³µ ν™•μΈ
    description: λ³Έ μ΄μκ°€ μ¤‘λ³µμ΄ μ•„λ‹μ§€ κ²€μƒ‰μ„ ν†µν•΄ ν™•μΈν•μ…¨λ‚μ”?
    placeholder: ν™•μΈν–μµλ‹λ‹¤.
  validations:
    required: true
- type: input
  id: category
  attributes:
    label: μΉ΄ν…κ³ λ¦¬
    description: μ¤νƒ€μΌ κ°€μ΄λ“ ν•­λ©μ— ν•΄λ‹Ήλλ” μΉ΄ν…κ³ λ¦¬λ¥Ό μ‘μ„±ν•΄μ£Όμ„Έμ”.
    placeholder: ex. Naming of Delegates, Closure Expressions
  validations:
    required: true
- type: textarea
  id: reason
  attributes:
    label: μμ • μ΄μ 
    description: ν•΄λ‹Ή λ‚΄μ©μ μμ • λ° μ‚­μ κ°€ ν•„μ”ν• μ΄μ λ¥Ό κ°„λ‹¨ν•κ² μ‘μ„±ν•΄μ£Όμ„Έμ”.
    placeholder: ex. λ³µμν•μ μ΄λ¦„μ„ sλ΅λ§ κµ¬λ¶„ν•λ©΄ λμ— μ λ„μ§€ μ•λ” κ²ƒ κ°™μ•„μ”
  validations:
    required: true
